version: '3'

services:

  pipeline:
    container_name: clams_pipeline
    image: clams-pipeline
    build:
      dockerfile: Dockerfile
      context: ../pipeline-runner
    stdin_open: true
    tty: true
    volumes:
      - "/private/var/archive:/data"
      - "./:/app/host"
    ports:
      - '5000:5000'

  tokenizer:
    image: clams-tokenizer
    build:
      dockerfile: Dockerfile
      context: ../app-nlp-example
    volumes:
      - "/data/clams/archive:/data"
    ports:
      - '5001:5000'

  spacy:
    image: clams-spacy
    build:
      dockerfile: Dockerfile
      context: ../app-spacy-nlp
    volumes:
      - "/data/clams/archive:/data"
    ports:
      - '5002:5000'
